version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use the Node.js version you need

  pre_build:
    commands:
      - echo "Fetching code from GitHub..."
      - git clone https://github.com/Shashank2712/node-todo-cicd-aws-pipeline.git || true
      - cd node-todo-cicd-aws-pipeline  # Navigate to your Node.js app directory
      - echo "Installing Node.js dependencies..."
      - npm install  # Use yarn if you prefer

  build:
    commands:
      - echo "Running tests..."  # You can replace this with actual test commands
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/your-node-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/your-node-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
